### ISSUE TITLE
I have sum sort of url redirection to asksusi.com from my local server.

### ISSUE THREAD

**Issue by smokingwheels** [loklak/asksusi_com#14]
I have sum sort of url redirection error on one of my servers [See Video](https://youtu.be/2utQqczdfQQ) 
Can you also confirm I do not have write access to this code?

**Comment by daminisatya** [comment]
@smokingwheels I have seen the video. I guess you dint take the latest code from asksusi which fixed the bug. [Observation ==> asksusi not giving response.]

**Comment by sudheesh001** [comment]
@smokingwheels I think this is a part of the latest changes , asksusi was moved out of loklak server and kept standalone. It has a redirect on it to the asksusi.com website.
```html
<!DOCTYPE html>
<!-- The original app code was removed. The app becomes a stand-alone web page, hosted at asksusi.com. The source code moved to https://github.com/loklak/asksusi_com -->
<html>
  <head>
    <meta charset="UTF-8">
    <title>asksusi.com</title>
    <meta http-equiv="REFRESH" content="1;URL=http://asksusi.com">
  </head>
  <body>
<SCRIPT LANGUAGE="JavaScript1.1"><!--
window.location= "http://asksusi.com";
//--></SCRIPT>
  </body>
</html>
```
