### ISSUE TITLE
Support for display of piecharts and tables

### ISSUE THREAD

**Issue by daminisatya** [loklak/asksusi_com#5]

**Comment by mariobehling** [comment]
Please provide a description with more details and how you plan to implement this.

**Comment by daminisatya** [comment]
@mariobehling Here is a sample data which returns data for piecharts
```
{
  "session": {"identity": {
    "type": "host",
    "name": "10.67.93.57",
    "anonymous": true
  }},
  "count": 1,
  "answers": [{
    "metadata": {
      "hits": 21,
      "offset": 0,
      "count": 2
    },
    "data": [
      {
        "percent": 50,
        "president": "hillary2016"
      },
      {
        "percent": 50,
        "president": "trump2016"
      }
    ],
    "actions": [
      {
        "expression": "I believe the next president will be hillary2016 with a likelihood of 50.0 percent but I a not sure.",
        "type": "answer"
      },
      {
        "total": 100,
        "unit": "%",
        "type": "piechart",
        "value": "percent",
        "key": "country"
      }
    ]
  }]
}
```
[Here](http://loklak.org/api/susi.json?q=Who will win the 2016 presidential election) is the sample link 

So we need to capture the data array objects and use this information to display the piecharts on the chart interface.

**Comment by daminisatya** [comment]
And for data like table here is a sample response.

```
{
  "session": {"identity": {
    "type": "host",
    "name": "127.0.0.1",
    "anonymous": true
  }},
  "count": 1,
  "answers": [{
    "data": [
      {"title": "programming"},
      {"title": "Datasets Archive"},
      {"title": "We collected 1.3 billion tweets with a distributed, peer-to-peer based free, open source twitter scraper that has a nice API for your self-made apps to evaluate the data: loklak.org"},
      {"title": "A look at Loklak.org and the Webclient progress"},
      {"title": "#Loklak Web client Test A Twitter search engine loklak.org"}
    ],
    "metadata": {"count": 5},
    "actions": [
      {
        "expression": "Here is the list of articles about loklak",
        "type": "answer"
      },
      {"type": "table"}
    ]
  }]
}
```
[Here](http://localhost:9000/api/susi.json q=What are the reddit articles about loklak) is the sample link , For this we have to make sure that the list is being displayed.

**Comment by daminisatya** [comment]
**How will i capture this info?** 

While defining the rules we have key point like for tables we have ```{“type“:“table“}]``` and for piecharts we have ```{“type“:“piechart“, “total“:100, “key“: “country“, “value“:“percent“, “unit“:“%“}]``` using which we can differentiate between the type of response and display accordingly.

**Comment by daminisatya** [comment]
@Orbiter currently the pie charts response is not available for the [sample query ](http://loklak.org/api/susi.json?q=Who%20will%20win%20the%202016%20presidential%20election) Till then i will work on displaying tables. Please give me another example which will return the percentages.
